' Creole Forth for VB
' Version 0.01
' Copyright 2021 Joseph M. O'Connor
' This Source Code Form is subject to the terms of the Mozilla Public
' License, v. 2.0. If a copy of the MPL was not distributed with this
' file, You can obtain one at http://mozilla.org/MPL/2.0/.

Option Explicit
Dim iReturnVal As Integer

' ( -- ) Do whatever you want here
Function DoTest(poGSP As GlobalSimpleProps)
    MsgBox "Testing"
    DoTest = 0
End Function
